// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.stat4you.crawler.util;

public class FileRepositoryContentBuilder extends FileRepositoryContentBuilderBase<FileRepositoryContentBuilder> {

    public static FileRepositoryContentBuilder fileRepositoryContent() {
        return new FileRepositoryContentBuilder();
    }

    public FileRepositoryContentBuilder() {
        super(new FileRepositoryContent());
    }

    public FileRepositoryContent build() {
        return getInstance();
    }
}

class FileRepositoryContentBuilderBase<GeneratorT extends FileRepositoryContentBuilderBase<GeneratorT>> {

    private FileRepositoryContent instance;

    protected FileRepositoryContentBuilderBase(FileRepositoryContent aInstance) {
        instance = aInstance;
    }

    protected FileRepositoryContent getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withId(String aValue) {
        instance.setId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPath(String aValue) {
        instance.setPath(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPxUpdate(String aValue) {
        instance.setPxUpdate(aValue);

        return (GeneratorT) this;
    }
}
