-- ###########################################
-- # Create new entities
-- ###########################################

-- Normal entities
    
CREATE TABLE TBL_INTERNATIONAL_STRINGS (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CONSTRAINT UNIQUE (ID)
	

)  ENGINE=InnoDB ;

CREATE TABLE TBL_CATEGORIES (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL,
  VALUE_FK BIGINT,
  PARENT_FK BIGINT,
  CONSTRAINT UNIQUE (ID)
	

)  ENGINE=InnoDB ;

CREATE TABLE TBL_LANGUAGES (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CODE VARCHAR(20) NOT NULL,
  VALUE_FK BIGINT,
  CONSTRAINT UNIQUE (ID)
	

)  ENGINE=InnoDB ;

CREATE TABLE TBL_LOCALISED_STRINGS (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  LABEL VARCHAR(4000) NOT NULL,
  LOCALE VARCHAR(10) NOT NULL,
  INTERNATIONAL_STRING_FK BIGINT,
  CONSTRAINT UNIQUE (ID)
	

)  ENGINE=InnoDB ;
-- Entity LocalisedStringEntity inverse referenced from InternationalStringEntity.texts
ALTER TABLE TBL_LOCALISED_STRINGS ADD CONSTRAINT FK_TBL_LOCALISED_STRINGS_TBL_INTERNATIONAL_STRINGS
	FOREIGN KEY (INTERNATIONAL_STRING_FK) REFERENCES TBL_INTERNATIONAL_STRINGS(ID);

-- Reference from CategoryEntity.VALUE_FK to InternationalStringEntity
ALTER TABLE TBL_CATEGORIES ADD CONSTRAINT FK_TBL_CATEGORIES_VALUE_FK
  FOREIGN KEY (VALUE_FK) REFERENCES TBL_INTERNATIONAL_STRINGS(ID);
-- Reference from CategoryEntity.PARENT_FK to CategoryEntity
ALTER TABLE TBL_CATEGORIES ADD CONSTRAINT FK_TBL_CATEGORIES_PARENT_FK
  FOREIGN KEY (PARENT_FK) REFERENCES TBL_CATEGORIES(ID);
  
-- Reference from LanguageEntity.VALUE_FK to InternationalStringEntity
ALTER TABLE TBL_LANGUAGES ADD CONSTRAINT FK_TBL_LANGUAGES_VALUE_FK
  FOREIGN KEY (VALUE_FK) REFERENCES TBL_INTERNATIONAL_STRINGS(ID);
  
  
	
-- Many to many relations

