ALTER TABLE TBL_LANGUAGES ADD UNIQUE LANGUAGE_CODE_UNIQUE(CODE);
ALTER TABLE TBL_CATEGORIES ADD UNIQUE CATEGORY_CODE_UNIQUE(CODE);
ALTER TABLE TBL_LOCALISED_STRINGS ADD UNIQUE LOCALE_UNIQUE(LOCALE, INTERNATIONAL_STRING_FK);
