    
-- ###########################################
-- # Drop entities
-- ###########################################

-- Many to many relations
    
-- Normal entities
DROP TABLE IF EXISTS TBL_LOCALISED_STRINGS;
DROP TABLE IF EXISTS TBL_CODES_DIMENSIONS;
DROP TABLE IF EXISTS TBL_ATTRIBUTES_DIMENSIONS;
DROP TABLE IF EXISTS TBL_DIMENSIONS;
DROP TABLE IF EXISTS TBL_ATTRIBUTES_DEFINITIONS;
DROP TABLE IF EXISTS TBL_DATASETS_VERSIONS;
DROP TABLE IF EXISTS TBL_PRIMARY_MEASURES;
DROP TABLE IF EXISTS TBL_DATASETS;
DROP TABLE IF EXISTS TBL_PROVIDERS;
DROP TABLE IF EXISTS TBL_INTERNATIONAL_STRINGS;
DROP TABLE IF EXISTS TBL_DATASETS_VISITED;
DROP TABLE IF EXISTS TBL_DATASETS_MOST_VISITED_TMP;
DROP TABLE IF EXISTS TBL_DATASETS_MOST_VISITED;