CREATE TABLE TBL_DATASETS_MOST_VISITED (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PROVIDER_ACRONYM VARCHAR(50) NOT NULL,
  DATASET_IDENTIFIER VARCHAR(255) NOT NULL,
  CONSTRAINT UNIQUE (ID)
	

)  ENGINE=InnoDB ;

CREATE TABLE TBL_DATASETS_MOST_VISITED_TMP (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PROVIDER_ACRONYM VARCHAR(50) NOT NULL,
  DATASET_IDENTIFIER VARCHAR(255) NOT NULL,
  CONSTRAINT UNIQUE (ID)
	

)  ENGINE=InnoDB ;

CREATE TABLE TBL_DATASETS_VISITED (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PROVIDER_ACRONYM VARCHAR(50) NOT NULL,
  DATASET_IDENTIFIER VARCHAR(255) NOT NULL,
  USER VARCHAR(200) NOT NULL,
  IP VARCHAR(50) NOT NULL,
  DATE DATETIME NOT NULL,
  CONSTRAINT UNIQUE (ID)
	

)  ENGINE=InnoDB ;

CREATE INDEX DATASET_PROVIDER_INDEX ON TBL_DATASETS_VISITED(DATASET_IDENTIFIER,PROVIDER_ACRONYM);
CREATE INDEX DATE_INDEX ON TBL_DATASETS_VISITED(DATE);
CREATE INDEX IP_INDEX ON TBL_DATASETS_VISITED(IP); 
