// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package org.siemac.metamac.portal.core.exporters.px;

import java.util.ArrayList;
import java.util.List;

public class PxLineContainerBuilder extends PxLineContainerBuilderBase<PxLineContainerBuilder> {

    public static PxLineContainerBuilder pxLineContainer() {
        return new PxLineContainerBuilder();
    }

    public PxLineContainerBuilder() {
        super(new PxLineContainer());
    }

    public PxLineContainer build() {
        return getInstance();
    }
}

class PxLineContainerBuilderBase<GeneratorT extends PxLineContainerBuilderBase<GeneratorT>> {

    private PxLineContainer instance;

    protected PxLineContainerBuilderBase(PxLineContainer aInstance) {
        instance = aInstance;
    }

    protected PxLineContainer getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPxKey(PxKeysEnum aValue) {
        instance.setPxKey(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withIndexedValue(List<String> aValue) {
        instance.setIndexedValue(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withAddedIndexedValueElement(String aValue) {
        if (instance.getIndexedValue() == null) {
            instance.setIndexedValue(new ArrayList<String>());
        }

        ((ArrayList<String>) instance.getIndexedValue()).add(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withLang(String aValue) {
        instance.setLang(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withValue(Object aValue) {
        instance.setValue(aValue);

        return (GeneratorT) this;
    }
}
