-- ###########################################
-- # Create new entities
-- ###########################################

-- Normal entities
    
CREATE TABLE TBL_USERS (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(200) NOT NULL,
  NAME VARCHAR(200) NOT NULL,
  SURNAME VARCHAR(500) NOT NULL,
  PASSWORD VARCHAR(50),
  MAIL VARCHAR(500),
  SEX VARCHAR(50),
  EDUCATION_LEVEL VARCHAR(500),
  BIRTHPLACE VARCHAR(500),
  PERMANENT_ADDRESS VARCHAR(4000),
  BIRTHDAY DATE,
  MARITAL_STATUS VARCHAR(500),
  OCCUPATION VARCHAR(500),
	REMOVED_DATE_TZ VARCHAR(50)
	,
  REMOVED_DATE DATETIME,
  UUID VARCHAR(36) NOT NULL,
	CREATED_DATE_TZ VARCHAR(50)
	,
  CREATED_DATE DATETIME,
  CREATED_BY VARCHAR(50),
	LAST_UPDATED_TZ VARCHAR(50)
	,
  LAST_UPDATED DATETIME,
  LAST_UPDATED_BY VARCHAR(50),
  VERSION BIGINT NOT NULL,
  CONSTRAINT UNIQUE (UUID)
  	

)  ENGINE=InnoDB ;
  
	
-- Many to many relations

