CREATE INDEX DATASET_PROVIDER_INDEX ON TBL_DATASETS_VISITED(DATASET_IDENTIFIER,PROVIDER_ACRONYM);
CREATE INDEX DATE_INDEX ON TBL_DATASETS_VISITED(DATE);
CREATE INDEX IP_INDEX ON TBL_DATASETS_VISITED(IP); 