Vagrant::Config.run do |config|
  config.vm.box = 'precise32'
  config.vm.box_url = 'http://files.vagrantup.com/precise32.box'
  config.vm.forward_port 8080, 8082

  config.vm.provision :shell, :path => "provisioner.sh"

  config.vm.share_folder "foo", "/home/vagrant/apache-tomcat-6.0.37/webapps/opencms/WEB-INF/jsp/online/system/modules/org.siemac.metamac.metamac-portal/formatters", "../metamac-portal-opencms/target/tmp/system/modules/org.siemac.metamac.metamac-portal/formatters"

end